ci:
  skip: [cargo-fmt, cargo-clippy]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: no-commit-to-branch
        args: ["--branch", "main"]
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo +nightly fmt --check
        language: system
        types: [rust]
        pass_filenames: false
      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy --all-targets --all-features --benches -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false
  - repo: https://github.com/woodruffw/zizmor-pre-commit
    rev: v1.22.0
    hooks:
      - id: zizmor
