name: docs

on:
  pull_request:
    paths:
      - .github/workflows/docs.yml
      - crates/**
      - Cargo.toml
      - Cargo.lock
  push:
    branches: [main]
    paths:
      - .github/workflows/docs.yml
      - crates/**
      - Cargo.toml
      - Cargo.lock
  workflow_call:

concurrency:
  group: docs-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  should-run:
    if: "${{ github.event_name != 'push' || !contains(github.event.head_commit.message, ':bookmark: release v') }}"
    runs-on: ubuntu-latest
    steps:
      - run: true

  build:
    runs-on: ubuntu-24.04
    needs: [should-run]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxkbcommon-dev

      - uses: actions-rust-lang/setup-rust-toolchain@1780873c7b576612439a134613cc4cc74ce5538c
        with:
          toolchain: nightly
          cache: true

      - name: Check docs build cleanly
        run: RUSTDOCFLAGS="-D warnings --cfg docsrs" cargo +nightly doc --workspace --no-deps
